name: Deploy on release

on:
  release:
    types: [published]

jobs:

  build-dockerfile:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - name: Build the Docker image
      env:
        CR_ID: ${{ secrets.CR_ID }}
        OAUTH_TOKEN: ${{ secrets.YC_OAUTH_TOKEN }}
      run: |
        docker login --username oauth --password $OAUTH_TOKEN cr.yandex
        docker build . --file Dockerfile --tag cr.yandex/$CR_ID/nginx-testapp:staging
        docker push cr.yandex/$CR_ID/nginx-testapp:staging

  deploy-to-k8s:
    runs-on: ubuntu-latest
    needs: build-dockerfile

    steps:

    - uses: actions/checkout@master

    - name: Setup kubernetes context
      uses: azure/k8s-set-context@v4
      with:
        method: service-account
        k8s-url: ${{ secrets.K8S_URL }}
        k8s-secret: ${{ secrets.K8S_SECRET }}

    - name: Deploy to cluster
      uses: Azure/k8s-deploy@v5
      with:
         namespace: kube-system
         action: deploy
         manifests: deployment.yml
